class Color

  def self.all
    [
      ['Aged Cappuccino','AC'],
      ['Aged Black','AB'],
      ['Aged Mesquite','AM'],
      ['Amaranth Purple','AP'],
      ['Amber Orange','AO'],
      ['American Red','AR'],
      ['American Blue','AE'],
      ['Antique White','AW'],
      ['Antique Brass','AN'],
      ['Apple Green','AG'],
      ['Black','BL'],
      ['Black Bronze','BB'],
      ['Brushed Nomad','BNO'],
      ['Brushed Apple Blossom','BAB'],
      ['Brushed Red (Lady Bug)','BRD'],
      ['Brushed Butterscotch','BS'],
      ['Brushed Weatherstone','BWS'],
      ['Brushed Wisteria','WI'],
      ['Brushed Antique Brass','BA'],
      ['Brushed Champagne','BG'],
      ['Brushed Metallic Cappuccino','BM'],
      ['Brushed Penny','BPN'],
      ['Brushed Marshland','BRM'],
      ['Brushed Spiced Orange','SO'],
      ['Bumble bee','YB'],
      ['Butterscotch','BS'],
      ['Burnt Clay','BCL'],
      ['Cappuccino','CP'],
      ['Celery','CL'],
      ['Champagne','CM'],
      ['Chalk','CK'],
      ['Chestnut','CT'],
      ['Cherry Red','CR'],
      ['Copper','CE'],
      ['Coffee Cream','CC'],
      ['Coffee','CF'],
      ['Dark Moss','DM'], 
      ['Dark Chocolate','DK'],
      ['Dark Red Brick','RB'],
      ['Festival Fuchsia','FF'],
      ['Festival Green','FG'],
      ['Festival Red','FR'],
      ['Flamingo','FL'],
      ['Galvanized Silver','GS'],
      ['Glitz Gold','GGO'],
      ['Glitz Black','GLB'],
      ['Glitz Green','GGR'],
      ['Glitz Silver','GGS'],
      ['Glitz Pink','GPI'],
      ['Glitz Purple','GPU'],
      ['Glitz Red','GRD'],
      ['Glossy Silver','GSI'],
      ['Glossy Red','GY'],
      ['Glossy Green','LG'],
      ['Godiva','GD'],
      ['Green','GR'],
      ['Gun metal Grey','GM'],
      ['Halloween Orange (Tangerine)','HO'],
      ['Iris','IR'],
      ['Lavender','LA'],
      ['Mahogany','MA'],
      ['Metallic Cappuccino','ME'],
      ['Milk Chocolate','MC'],
      ['Mocha','MH'],
      ['Mustard Grain','MD'],
      ['Mystic Green','MG'],
      ['Nomad','NO'],
      ['Olive','OL'],
      ['Orange','OR'],
      ['Patina Copper','PC'],
      ['Penny','PN'],
      ['Pewter','PT'],
      ['Peridot','PE'],
      ['Pink','PI'],
      ['Pomegranate','PM'],
      ['Purple','PU'],
      ['Rose Pink','RP'],
      ['Rust','RT'],
      ['Sandstone','SS'],
      ['Seascape Grey','BSG'],
      ['Seascape Blue','SC'],
      ['Silver','SI'],
      ['Sky Blue','SB'],
      ['Sparkle Black','SBL'],
      ['Sparkle Gold','SG '],
      ['Sparkle Green','SN'],
      ['Sparkle Pink','SPI'],
      ['Sparkle Purple','SPU'],
      ['Sparkle Red','SR'],
      ['Sparkle Silver','SSI'],
      ['Terra Cotta','TC'],
      ['Teal','TL'],
      ['Verdigris','VG'],
      ['Vintage Gold','GV'],
      ['Vintage Red','RV'],
      ['Vintage Green','VE'],
      ['Vintage Silver','VS'],
      ['Warm Copper','WC'],
      ['Walnut','WA'],
      ['Weathered Stone','WS'],
      ['White','WH'],
      ['Wheat','WT'],
      ['Wood','WD'],
      ['Yellow','YW']
    ]
  end

  def self.name_for_abbr abbr
    if color = all.find { |color| color.last == abbr }
      color.first
    end
  end

end
